const listDB = [
  {
    id: 1,
    name: "234",
    inn: "324",
    ogrn: "43",
    bik: "цук",
    r_s: "324",
    k_s: "324",
    bank: "цук",
    phoneNumber: "24234",
    address: "ук",
    comment: "324",
    numberOfDeliveries: "13",
    amountOfDeliveries: "100",
    outstandingPayment: "",
    idPos: 1,
    namePos: "жучка продаж",
  },
  {
    id: 2,
    name: "23",
    inn: "324",
    ogrn: "432342432",
    bik: "3434",
    r_s: "",
    k_s: "",
    bank: "324",
    phoneNumber: "323324",
    address: "432432",
    comment: "",
    numberOfDeliveries: "123",
    amountOfDeliveries: "456",
    outstandingPayment: "",
    idPos: 1,
    namePos: "кочка продаж",
  },
  {
    id: 4,
    name: "cdsc",
    inn: "",
    ogrn: "",
    bik: "",
    r_s: "",
    k_s: "",
    bank: "",
    phoneNumber: "",
    address: "",
    comment: "",
    numberOfDeliveries: "453",
    amountOfDeliveries: "2345",
    outstandingPayment: "",
    idPos: 1,
    namePos: "бочка продаж",
  },
  {
    id: 5,
    name: "цу",
    inn: "",
    ogrn: "",
    bik: "",
    r_s: "",
    k_s: "",
    bank: "",
    phoneNumber: "",
    address: "",
    comment: "",
    numberOfDeliveries: "5235",
    amountOfDeliveries: "12",
    outstandingPayment: "",
    idPos: 1,
    namePos: "Точка продаж",
  },
  {
    id: 3,
    name: "234",
    inn: "32432",
    ogrn: "",
    bik: "",
    r_s: "",
    k_s: "",
    bank: "",
    phoneNumber: "324324",
    address: "4324",
    comment: "",
    numberOfDeliveries: "765",
    amountOfDeliveries: "4",
    outstandingPayment: "",
    idPos: 20,
    namePos: "dsf",
  },
  {
    id: 6,
    name: "ваппавып",
    inn: "",
    ogrn: "",
    bik: "",
    r_s: "",
    k_s: "",
    bank: "",
    phoneNumber: "",
    address: "",
    comment: "",
    numberOfDeliveries: "8754",
    amountOfDeliveries: "1234",
    outstandingPayment: "",
    idPos: 20,
    namePos: "dsf",
  },
];

export const getAllList = () => listDB;
