const listDB = [
  {
    main: false,
    id: 1,
    name: "Основной склад",
    legalEntity: "Краткая юридическая информация",
    restaurant: "Название точки продаж",
    idPos: 0,
    cli: 1,
    typeWarehouse: 0,
    stockItems: [
      {
        id: 1,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "21",
        gross: -9000,
        name: "Тест",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 2,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "test",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 3,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "New Brand",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 8,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "1111111111111111111111111111111fgbfgbfgbfgb",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 9,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "Мука",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 10,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "Кунжут",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 11,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "2",
        calories: "",
        gross: 0,
        name: "Тест 44",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 22,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "5",
        fats: "4",
        carbohydrates: "7",
        calories: "84",
        gross: 0,
        name: "ингредиент в кг",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 23,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "ингредиент в литрах",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 3,
          name: "л",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 24,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "ингредиент в в шт",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 25,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "тест 55",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 26,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "вамавм",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 27,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "5",
        fats: "5",
        carbohydrates: "6",
        calories: "",
        gross: 0,
        name: "fgvgf",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 28,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "5",
        fats: "3",
        carbohydrates: "6",
        calories: "",
        gross: 0,
        name: "fgvf",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 29,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "4",
        fats: "4",
        carbohydrates: "4",
        calories: "",
        gross: 0,
        name: "кунжут 2",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 30,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "2",
        fats: "2",
        carbohydrates: "3",
        calories: "",
        gross: 0,
        name: "тестhnjm",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 31,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "4",
        carbohydrates: "5",
        calories: "",
        gross: 0,
        name: "jknkm",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 32,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "2",
        fats: "3",
        carbohydrates: "4",
        calories: "",
        gross: 0,
        name: "лшщзд",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 3,
          name: "л",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 33,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "5",
        carbohydrates: "5",
        calories: "",
        gross: 0,
        name: "кунжутjkhj",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 34,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "4",
        fats: "3",
        carbohydrates: "4",
        calories: "",
        gross: 0,
        name: "кунжутk",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 35,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "4",
        carbohydrates: "4",
        calories: "",
        gross: 0,
        name: "gfhf",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 36,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "4",
        fats: "3",
        carbohydrates: "5",
        calories: "",
        gross: 0,
        name: "ghj",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 37,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "5",
        fats: "4",
        carbohydrates: "5",
        calories: "",
        gross: 0,
        name: "jhjhg",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 3,
          name: "л",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 38,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "тест 111",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 39,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "fffggg",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 40,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "тест 66",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 41,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "роллыcdcdcd",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 42,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "рисdfv",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 3,
          name: "л",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 43,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "2",
        fats: "2",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "цуа",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 44,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "wef",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 45,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "w3d3w",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 46,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "wefe",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 47,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "2",
        fats: "3",
        carbohydrates: "4",
        calories: "",
        gross: 0,
        name: "wefwdwd",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 48,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "erfr",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 49,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "rtgrt",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 50,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "erfer",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 51,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "wefeee",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 52,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "45t",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 53,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "dfvdfv",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 54,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "4",
        fats: "4",
        carbohydrates: "4",
        calories: "",
        gross: 0,
        name: "кунжутlm",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 3,
          name: "л",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 55,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "erf",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 56,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "sdcs",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 57,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "2",
        calories: "",
        gross: 0,
        name: "dfvf",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 58,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "тест 33",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 59,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "тест 664",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 60,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "sdfs",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 61,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "4",
        fats: "4",
        carbohydrates: "5",
        calories: "",
        gross: 0,
        name: "erfererf",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 62,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "6",
        fats: "5",
        carbohydrates: "3",
        calories: "",
        gross: 0,
        name: "рисwed",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 63,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "sdcsdcsdc",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 64,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "dfrg",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 65,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "sdc",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 66,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "5",
        carbohydrates: "5",
        calories: "",
        gross: 0,
        name: "sdcsdcds",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 67,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "арптаапр",
        cli: 0,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 68,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "тестовый ингредиент 1",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 69,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "тестовый ингредиент 2",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 70,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "Тест 444",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 71,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "куакау",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 72,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "2",
        carbohydrates: "1",
        calories: "",
        gross: 0,
        name: "укакуа",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 77,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "Кока-кола 0.5",
        cli: 0,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 78,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "3",
        carbohydrates: "5",
        calories: "",
        gross: 0,
        name: "кунжут mn",
        cli: 0,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 79,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "Рис3d3d3",
        cli: 0,
        warehouse: "Основной склад",
        unit: {
          id: 2,
          name: "шт",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 80,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "5",
        carbohydrates: "7",
        calories: "85",
        gross: 0,
        name: "кунжутrr",
        cli: 1,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 82,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "4",
        carbohydrates: "5",
        calories: "68",
        gross: 5000,
        name: "ыва",
        cli: 0,
        warehouse: "Основной склад",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
    ],
    typeWarehouses: "STANDART",
  },
  {
    main: true,
    id: 2,
    name: "Основной складТочка продаж бананов",
    legalEntity: "Краткая юридическая информация",
    restaurant: "asd",
    idPos: 0,
    cli: 1,
    typeWarehouse: 0,
    stockItems: [
      {
        id: 5,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "тест",
        cli: 1,
        warehouse: "Основной складТочка продаж бананов",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 6,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "21",
        gross: 0,
        name: "тест",
        cli: 1,
        warehouse: "Основной складТочка продаж бананов",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
    ],
    typeWarehouses: "STANDART",
  },
  {
    main: true,
    id: 3,
    name: "Основной складТестовая точка продаж 1",
    legalEntity: "Краткая юридическая информация",
    restaurant: " sdf",
    idPos: 0,
    cli: 1,
    typeWarehouse: 0,
    stockItems: [
      {
        id: 4,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "21",
        gross: 0,
        name: "тест",
        cli: 1,
        warehouse: "Основной складТестовая точка продаж 1",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 7,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "тест",
        cli: 1,
        warehouse: "Основной складТестовая точка продаж 1",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 84,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "2",
        carbohydrates: "1",
        calories: "",
        gross: 5000,
        name: "укакуа",
        cli: 0,
        warehouse: "Основной складТестовая точка продаж 1",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
    ],
    typeWarehouses: "STANDART",
  },
  {
    main: true,
    id: 18,
    name: "Основной складsadaasd",
    legalEntity: "Краткая юридическая информация",
    restaurant: "",
    idPos: 0,
    cli: 1,
    typeWarehouse: 0,
    stockItems: [
      {
        id: 12,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "1",
        fats: "1",
        carbohydrates: "1",
        calories: "21",
        gross: -3432000,
        name: "тест",
        cli: 1,
        warehouse: "Основной складsadaasd",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 17,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "",
        fats: "",
        carbohydrates: "",
        calories: "",
        gross: 0,
        name: "1111111111111111111111111111111fgbfgbfgbfgb",
        cli: 1,
        warehouse: "Основной складsadaasd",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
      {
        id: 83,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "4",
        carbohydrates: "5",
        calories: "68",
        gross: 5000,
        name: "ыва",
        cli: 0,
        warehouse: "Основной складsadaasd",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
    ],
    typeWarehouses: "STANDART",
  },
  {
    main: false,
    id: 27,
    name: "авп",
    legalEntity: "чпв",
    restaurant: "ачвп",
    idPos: 0,
    cli: 1,
    typeWarehouse: 0,
    stockItems: [
      {
        id: 81,
        priceForOne: "0",
        priceForAll: "0",
        proteins: "3",
        fats: "4",
        carbohydrates: "5",
        calories: "68",
        gross: -34000,
        name: "ыва",
        cli: 1,
        warehouse: "авп",
        unit: {
          id: 1,
          name: "кг",
        },
        type: "NOTHING",
        idWarehouses: 0,
      },
    ],
    typeWarehouses: "STANDART",
  },
  {
    main: false,
    id: 28,
    name: "вп",
    legalEntity: "вап",
    restaurant: "авп",
    idPos: 0,
    cli: 1,
    typeWarehouse: 0,
    stockItems: [],
    typeWarehouses: "STANDART",
  },
  {
    main: false,
    id: 29,
    name: "sdsf",
    legalEntity: "sdf",
    restaurant: "dsf",
    idPos: 0,
    cli: 1,
    typeWarehouse: 0,
    stockItems: [],
    typeWarehouses: "STANDART",
  },
];

export const getAllList = () => listDB;
